apiVersion: v1
kind: Namespace
metadata:
  name: sbtm-staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: sbtm-production
  labels:
    environment: production
