apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sbtm-ingress
  namespace: sbtm-demo-gcp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.demo-gcp.sbtm.example.com
      secretName: sbtm-tls-demo-gcp
  rules:
    - host: api.demo-gcp.sbtm.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
